### PR TITLE
Fix a bug can be occurred when `instance` returns `nil`

### PR DESCRIPTION
**Pull request by Kuniwak**
I got the following error message ([full error message](https://gist.github.com/Kuniwak/83e60be11445d1f859a5e58590c78afa)) when executing `kitchen list`:

```console
$ kitchen list
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::ClientError
>>>>>> Message: Could not load the 'vagrant' driver from the load path. Please ensure that your driver is installed as a gem or included in your Gemfile if using Bundler.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

This message said that "`kitchen-vagrant` was not installed," but `kitchen-vagrant` was listed by `bundle list` and `require("kitchen/driver/vagrant.rb")` did not raise `LoadError`.

I think this problem is caused by e788314e0c846765da8358619a87e2128bdab955. After this commit, the error ``undefined method `name' for nil:NilClass`` can be occurred when `instance` returns `nil`, because `instance.name` is accessed before `nil` check for `instance`.

### CODE REVIEW

**Comment by cheeseplus** [comment]
Thanks for the catch and the added test, I was moving things around for the style checker but I can see how that would have broken it.

**Comment by Kuniwak** [comment]
Thank you for the quick response!

**Comment by cheeseplus** [comment]
As soon as I saw the code and your explanation I realized that while it passed the tests, it's only because we weren't testing for that specific condition. I'll get a 1.02 release out ASAP.

**Comment by cheeseplus** [comment]
1.0.2 is released and thanks again @Kuniwak
