### ISSUE TITLE
Vagrant & Bundler 1.6

### ISSUE THREAD

**Issue by maoueh** [test-kitchen/kitchen-vagrant#94]
Vagrant is not ready to work with bundler 1.6 yet. See [issue #3451](https://github.com/mitchellh/vagrant/issues/3451) for more info. When vagrant is used with bundler 1.6 in a bundle environment, it crashes with the following message:

```
C:/Local/Vagrant/1.5.2/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/bundler.rb:38:in `init!': undefined method `new' for Bundler::UI:Module (NoMethodError)
        from C:/Local/Vagrant/1.5.2/embedded/gems/gems/vagrant-1.5.2/lib/vagrant/pre-rubygems.rb:22:in `<main>'
```

However, when using bundler 1.6 and `kitchen-vagrant`, the following error is reported instead:

```
>>>>>> ------Exception-------
>>>>>> Class: Kitchen::UserError
>>>>>> Message: Detected an old version of Vagrant (). Please upgrade to version 1.1.0 or higher from http://downloads.vagrantup.com/.
>>>>>> ----------------------
>>>>>> Please see .kitchen/logs/kitchen.log for more details
>>>>>> Also try running `kitchen diagnose --all` for configuration
```

Which is quite misleading. Checking the exit code would be a good improvement but I'm not sure it "feasible" in this environment. I'm reporting mainly so other users can find it when faced with such message. Feel free to close issue if won't fix.

And thank you for `test-kitchen` in general.

Regards,
Matt
